### PR TITLE
Users stories

### PR DESCRIPTION
**Pull request by Laetijo**

### CODE REVIEW

**Comment by 2trc** [comment]
Hi @Laetijo and thanks for your first contribution
I would suggest to post your idea in "Issues" first so we can have a discussion to better understand your proposal
https://github.com/2trc/katika/issues

**Comment by Laetijo** [comment]
Thank you @2trc for your feedback. I will get back to you as soon as I am done.

**Comment by Laetijo** [comment]
Hi @2trc 
I have finished creating all the issues. I am waiting for any exchange concerning my proposals.

**Comment by Laetijo** [comment]
Hello Remi,
I hope that you are well. Sorry, I know you are very busy. I just want to
remind you that I created all the issues.  So I'm waiting to  talk
about it..

Le jeu. 23 févr. 2023 à 18:16, Remi Tassing ***@***.***> a
écrit :

**Pull request closed without merging**
